---

- name: Install required packages
  action: >
    {{ ansible_pkg_mgr }} name=dconf-editor state=present
  become: yes

- include_tasks: set_value.yml
  vars:
    dconf_key: '{{ item.key }}'
    dconf_value: '{{ item.value }}'
  with_items: '{{ dconf_settings }}'
