---
# tasks file for dconf-settings

- name: Install required packages
  dnf:
    name: dconf-editor
    state: present
  become: yes

- include_tasks: set_value.yml
  vars:
    dconf_key: "{{ item.key }}"
    dconf_value: "{{ item.value }}"
  with_items: "{{ dconf_settings }}"
